# Generated by Django 6.0.7 on 2026-07-15 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome identificativo del contenitore (es. 'Camion A-123').", max_length=128, unique=True)),
                ('tipo_mezzo', models.CharField(choices=[('autocarro', 'Autocarro'), ('autotreno', 'Autotreno'), ('bilico', 'Autoarticolato (Bilico)'), ('furgone', 'Furgone'), ('nave', 'Nave'), ('treno', 'Treno (Carro ferroviario)'), ('container_20', "Container ISO 20'"), ('container_40', "Container ISO 40'"), ('container_40_hc', "Container ISO 40' High Cube"), ('altro', 'Altro / Personalizzato')], default='altro', help_text='Tipologia del mezzo di trasporto.', max_length=24)),
                ('lunghezza_mm', models.PositiveIntegerField(help_text='Lunghezza interna (asse X) in millimetri.', validators=[django.core.validators.MinValueValidator(1)])),
                ('larghezza_mm', models.PositiveIntegerField(help_text='Larghezza interna (asse Y) in millimetri.', validators=[django.core.validators.MinValueValidator(1)])),
                ('altezza_mm', models.PositiveIntegerField(help_text='Altezza interna (asse Z) in millimetri.', validators=[django.core.validators.MinValueValidator(1)])),
                ('carico_massimo_kg', models.DecimalField(decimal_places=2, help_text='Peso massimo trasportabile in chilogrammi.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tara_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso a vuoto del contenitore/veicolo in chilogrammi.', max_digits=8)),
                ('note', models.TextField(blank=True, help_text='Note opzionali (es. portellone, pianale, allestimento).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenitore',
                'verbose_name_plural': 'Contenitori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text="Codice univoco dell'oggetto (es. SKU, barcode, part number).", max_length=64, unique=True)),
                ('descrizione', models.TextField(blank=True, help_text="Descrizione dell'oggetto.")),
                ('lunghezza_mm', models.PositiveIntegerField(help_text='Dimensione X (lunghezza) in millimetri.', validators=[django.core.validators.MinValueValidator(1)])),
                ('larghezza_mm', models.PositiveIntegerField(help_text='Dimensione Y (larghezza) in millimetri.', validators=[django.core.validators.MinValueValidator(1)])),
                ('altezza_mm', models.PositiveIntegerField(help_text='Dimensione Z (altezza) in millimetri.', validators=[django.core.validators.MinValueValidator(1)])),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text="Peso dell'oggetto in chilogrammi.", max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantita_disponibile', models.PositiveIntegerField(default=1, help_text='Quantità disponibile in magazzino (per oggetti multipli).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oggetto',
                'verbose_name_plural': 'Oggetti',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='PianoDiCarico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome identificativo del piano di carico (es. 'Spedizione #42').", max_length=128)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('in_elaborazione', 'In elaborazione'), ('completato', 'Completato'), ('parziale', 'Completato parzialmente'), ('fallito', 'Nessuna soluzione trovata'), ('errore', "Errore durante l'elaborazione")], default='bozza', help_text='Stato del processo di ottimizzazione.', max_length=24)),
                ('peso_totale_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Peso totale del carico (calcolato dopo l'ottimizzazione).", max_digits=10, null=True)),
                ('volume_utilizzato_mm3', models.PositiveBigIntegerField(blank=True, help_text="Volume totale occupato in mm³ (calcolato dopo l'ottimizzazione).", null=True)),
                ('task_id', models.CharField(blank=True, help_text='ID del task asincrono (coda) associato a questa elaborazione.', max_length=255, null=True)),
                ('messaggio_errore', models.TextField(blank=True, help_text="Eventuale messaggio di errore se l'elaborazione fallisce.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completato_at', models.DateTimeField(blank=True, help_text="Timestamp di completamento dell'elaborazione.", null=True)),
                ('contenitore', models.ForeignKey(help_text='Il contenitore/veicolo utilizzato per questo carico.', on_delete=django.db.models.deletion.PROTECT, related_name='piani_di_carico', to='caricamento.contenitore')),
            ],
            options={
                'verbose_name': 'Piano di Carico',
                'verbose_name_plural': 'Piani di Carico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OggettoPosizionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinata_x_mm', models.PositiveIntegerField(help_text="Coordinata X (lunghezza) dello spigolo d'ancoraggio in mm.")),
                ('coordinata_y_mm', models.PositiveIntegerField(help_text="Coordinata Y (larghezza) dello spigolo d'ancoraggio in mm.")),
                ('coordinata_z_mm', models.PositiveIntegerField(help_text="Coordinata Z (altezza) dello spigolo d'ancoraggio in mm.")),
                ('dimensione_x_mm', models.PositiveIntegerField(help_text='Dimensione effettiva X (dopo rotazione) in mm.', validators=[django.core.validators.MinValueValidator(1)])),
                ('dimensione_y_mm', models.PositiveIntegerField(help_text='Dimensione effettiva Y (dopo rotazione) in mm.', validators=[django.core.validators.MinValueValidator(1)])),
                ('dimensione_z_mm', models.PositiveIntegerField(help_text='Dimensione effettiva Z (dopo rotazione) in mm.', validators=[django.core.validators.MinValueValidator(1)])),
                ('rotazione_applicata', models.CharField(default='XYZ', help_text="Permutazione degli assi applicata all'oggetto. Es. 'XYZ' = originale, 'YXZ' = X e Y scambiati.", max_length=3)),
                ('colore', models.CharField(default='#4488ff', help_text='Colore esadecimale (es. #FF5733) per la visualizzazione 3D.', max_length=7)),
                ('peso_posato_sopra_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso cumulativo degli oggetti appoggiati sopra questo (calcolato).', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oggetto', models.ForeignKey(help_text="L'oggetto che è stato posizionato.", on_delete=django.db.models.deletion.PROTECT, related_name='posizionamenti', to='caricamento.oggetto')),
                ('piano_di_carico', models.ForeignKey(help_text='Il piano di carico a cui appartiene questo posizionamento.', on_delete=django.db.models.deletion.CASCADE, related_name='oggetti_posizionati', to='caricamento.pianodicarico')),
            ],
            options={
                'verbose_name': 'Oggetto Posizionato',
                'verbose_name_plural': 'Oggetti Posizionati',
                'ordering': ['piano_di_carico', 'coordinata_z_mm', 'coordinata_y_mm', 'coordinata_x_mm'],
            },
        ),
        migrations.CreateModel(
            name='VincoloOggetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotazione_consentita', models.BooleanField(default=True, help_text="Se True, l'oggetto può essere ruotato liberamente su qualsiasi asse. Se False, l'oggetto mantiene l'orientamento originale (X, Y, Z fissi).")),
                ('rotazione_su_x', models.BooleanField(default=True, help_text='Permette rotazione che scambia la dimensione X con Y.')),
                ('rotazione_su_y', models.BooleanField(default=True, help_text='Permette rotazione che scambia la dimensione Y con Z.')),
                ('rotazione_su_z', models.BooleanField(default=True, help_text='Permette rotazione che scambia la dimensione Z con X.')),
                ('sovrapponibile', models.BooleanField(default=True, help_text="Se True, l'oggetto può sostenere altri oggetti sopra di sé. Es. scatole di cartone sì, un carico di tubi no.")),
                ('peso_massimo_tetto_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso massimo (in kg) che questo oggetto può sopportare sul suo piano superiore. 0 = nessun limite (se sovrapponibile).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fragile', models.BooleanField(default=False, help_text="Indica se l'oggetto è fragile (es. 'Questo lato verso l'alto').")),
                ('merce_pericolosa', models.BooleanField(default=False, help_text="Indica se l'oggetto è una merce pericolosa (ADR/IMO).")),
                ('solo_su_piano', models.BooleanField(default=False, help_text="Se True, l'oggetto deve essere posizionato direttamente sul pavimento del contenitore (non sopra altri oggetti).")),
                ('aggancio_forche', models.BooleanField(default=False, help_text="Se True, l'oggetto può essere movimentato con carrello elevatore.")),
                ('note', models.TextField(blank=True, help_text='Note aggiuntive sui vincoli di carico.')),
                ('oggetto', models.OneToOneField(help_text='Oggetto a cui appartengono questi vincoli.', on_delete=django.db.models.deletion.CASCADE, related_name='vincoli', to='caricamento.oggetto')),
            ],
            options={
                'verbose_name': 'Vincolo Oggetto',
                'verbose_name_plural': 'Vincoli Oggetti',
            },
        ),
    ]
