# Generated by Django 6.0.7 on 2026-07-15 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenitore',
            name='carico_massimo_kg',
            field=models.DecimalField(decimal_places=2, help_text='Peso massimo trasportabile in chilogrammi.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, help_text="Peso dell'oggetto in chilogrammi.", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
