# Generated by Django 6.0.7 on 2026-07-15 07:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0002_alter_contenitore_carico_massimo_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OggettoDaCaricare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1, help_text='Quante unità di questo oggetto caricare.', validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.CharField(blank=True, help_text='Note opzionali per questo caricamento.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oggetto', models.ForeignKey(help_text="L'oggetto da caricare.", on_delete=django.db.models.deletion.PROTECT, related_name='da_caricare_in_piani', to='caricamento.oggetto')),
                ('piano_di_carico', models.ForeignKey(help_text="Piano di carico a cui aggiungere l'oggetto.", on_delete=django.db.models.deletion.CASCADE, related_name='oggetti_da_caricare', to='caricamento.pianodicarico')),
            ],
            options={
                'verbose_name': 'Oggetto da Caricare',
                'verbose_name_plural': 'Oggetti da Caricare',
                'ordering': ['piano_di_carico', 'oggetto__codice'],
                'unique_together': {('piano_di_carico', 'oggetto')},
            },
        ),
    ]
