# Generated by Django 6.0.7 on 2026-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0003_oggettodacaricare'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='colore',
            field=models.CharField(blank=True, default='', help_text='Colore esadecimale personalizzato (es. #FF5733). Vuoto = assegnazione automatica.', max_length=7),
        ),
    ]
