# Generated by Django 6.0.7 on 2026-07-15 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0004_aggiunto_colore_oggetto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VincoloTraOggetti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relazione', models.CharField(choices=[('non_sopra', 'A non può stare sopra B'), ('sopra', 'A deve stare sopra B'), ('vicino', 'A deve stare vicino a B'), ('lontano', 'A deve stare lontano da B'), ('prima', 'A deve essere caricato prima di B'), ('dopo', 'A deve essere caricato dopo B'), ('entro', 'A deve stare entro X cm da B'), ('almeno', 'A deve stare almeno Y cm lontano da B')], help_text='Tipo di vincolo tra A e B.', max_length=20)),
                ('parametro_distanza_cm', models.FloatField(blank=True, help_text="Distanza in cm (per vincoli 'entro X cm' e 'almeno Y cm').", null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('parametro_priorita', models.PositiveSmallIntegerField(blank=True, help_text='Priorità del vincolo (1 = massima).', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('attivo', models.BooleanField(default=True, help_text='Se False, il vincolo è disattivato e non applicato.')),
                ('note', models.TextField(blank=True, help_text='Note opzionali sul vincolo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oggetto_a', models.ForeignKey(help_text='Oggetto A della relazione.', on_delete=django.db.models.deletion.CASCADE, related_name='vincoli_come_a', to='caricamento.oggetto')),
                ('oggetto_b', models.ForeignKey(help_text='Oggetto B della relazione.', on_delete=django.db.models.deletion.CASCADE, related_name='vincoli_come_b', to='caricamento.oggetto')),
            ],
            options={
                'verbose_name': 'Vincolo tra Oggetti',
                'verbose_name_plural': 'Vincoli tra Oggetti',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('oggetto_a', 'oggetto_b', 'tipo_relazione'), name='unique_vincolo_tra_oggetti')],
            },
        ),
    ]
