# Generated by Django 6.0.7 on 2026-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0005_vincolo_tra_oggetti'),
    ]

    operations = [
        migrations.AddField(
            model_name='vincolotraoggetti',
            name='dettagli_posizionamento',
            field=models.JSONField(blank=True, default=None, help_text="Dettagli della configurazione di posizionamento. Formato: {configurazioni_valide: [{rotA: 'LxPxH', rotB: 'LxPxH'}], configurazione_selezionata: null|int}.", null=True),
        ),
    ]
