# Generated by Buffy - Mantiene solo SOPRA nei vincoli tra oggetti

from django.db import migrations, models
import django.core.validators


def elimina_vincoli_non_sopra(apps, schema_editor):
    """Elimina tutti i VincoloTraOggetti con tipo_relazione diverso da 'sopra'."""
    VincoloTraOggetti = apps.get_model("caricamento", "VincoloTraOggetti")
    cancellati = VincoloTraOggetti.objects.exclude(tipo_relazione="sopra").delete()[0]
    if cancellati:
        print(f"  ✓ Eliminati {cancellati} vincoli legacy (non-SOPRA)")


class Migration(migrations.Migration):

    dependencies = [
        ("caricamento", "0006_aggiunto_dettagli_posizionamento_vincolo_tra"),
    ]

    operations = [
        # Passo 1: cancella i dati non-SOPRA
        migrations.RunPython(
            elimina_vincoli_non_sopra,
            reverse_code=migrations.RunPython.noop,
        ),
        # Passo 2: rimuovi i campi orfani
        migrations.RemoveField(
            model_name="vincolotraoggetti",
            name="parametro_distanza_cm",
        ),
        migrations.RemoveField(
            model_name="vincolotraoggetti",
            name="parametro_priorita",
        ),
        # Passo 3: altera le choices di tipo_relazione — solo SOPRA
        migrations.AlterField(
            model_name="vincolotraoggetti",
            name="tipo_relazione",
            field=models.CharField(
                choices=[("sopra", "A deve stare sopra B")],
                max_length=20,
                help_text="Tipo di vincolo tra A e B.",
            ),
        ),
    ]
