# Generated by Django 6.0.7 on 2026-07-21 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0007_pulisci_vincoli_solo_sopra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SezioneCarico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome descrittivo (es. 'Zona 1 - Tridem anteriore').", max_length=64)),
                ('inizio_x_mm', models.PositiveIntegerField(help_text="Inizio della zona sull'asse X (lunghezza) in mm. Deve partire da 0.")),
                ('fine_x_mm', models.PositiveIntegerField(help_text="Fine della zona sull'asse X in mm. Deve essere > inizio.")),
                ('carico_massimo_kg', models.DecimalField(decimal_places=2, help_text='Carico massimo ammissibile per questa sezione in kg.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('contenitore', models.ForeignKey(help_text='Il contenitore/veicolo a cui appartiene questa sezione.', on_delete=django.db.models.deletion.CASCADE, related_name='sezioni', to='caricamento.contenitore')),
            ],
            options={
                'verbose_name': 'Sezione di Carico',
                'verbose_name_plural': 'Sezioni di Carico',
                'ordering': ['inizio_x_mm'],
            },
        ),
    ]
