# Generated by Django 6.0.7 on 2026-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0008_sezione_carico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pianodicarico',
            name='algoritmo',
            field=models.CharField(blank=True, default='', help_text="Nome dell'algoritmo utilizzato per l'ottimizzazione.", max_length=128),
        ),
    ]
