# Generated by Django 6.0.7 on 2026-07-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0009_aggiunto_algoritmo_piano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggettodacaricare',
            name='oggetto',
            field=models.ForeignKey(help_text="L'oggetto da caricare.", on_delete=django.db.models.deletion.CASCADE, related_name='da_caricare_in_piani', to='caricamento.oggetto'),
        ),
        migrations.AlterField(
            model_name='oggettoposizionato',
            name='oggetto',
            field=models.ForeignKey(help_text="L'oggetto che è stato posizionato.", on_delete=django.db.models.deletion.CASCADE, related_name='posizionamenti', to='caricamento.oggetto'),
        ),
    ]
