# Generated by Django 6.0.7 on 2026-07-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0010_cambia_on_delete_oggetto_in_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggettoposizionato',
            name='oggetto',
            field=models.ForeignKey(help_text="L'oggetto che è stato posizionato. PROTECT: non si può eliminare un oggetto se è posizionato in un piano di carico.", on_delete=django.db.models.deletion.PROTECT, related_name='posizionamenti', to='caricamento.oggetto'),
        ),
    ]
