# Generated by Django 6.0.7 on 2026-07-31 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0011_protect_oggetto_posizionato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oggettodacaricare',
            options={'ordering': ['piano_di_carico', 'priorita', 'oggetto__codice'], 'verbose_name': 'Oggetto da Caricare', 'verbose_name_plural': 'Oggetti da Caricare'},
        ),
        migrations.AddField(
            model_name='oggettodacaricare',
            name='priorita',
            field=models.PositiveSmallIntegerField(default=0, help_text='Priorità di carico (1 = massima priorità, caricato per primo). 0 = nessuna priorità.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
