# Generated by Django 5.2.1 on 2026-08-02 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0012_aggiunto_priorita_oggetto_da_caricare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorni_prova', models.PositiveIntegerField(default=14, help_text='Durata del periodo di prova in giorni (default: 14).')),
                ('demo_attiva', models.BooleanField(default=True, help_text='Se attivo, gli utenti possono accedere con account demo.')),
                ('google_oauth_attivo', models.BooleanField(default=False, help_text="Abilita il pulsante 'Accedi con Google' sulla landing page.")),
                ('google_client_id', models.CharField(blank=True, help_text='Client ID OAuth2 da Google Cloud Console.', max_length=255)),
                ('google_client_secret', models.CharField(blank=True, help_text='Client Secret OAuth2 da Google Cloud Console.', max_length=255)),
                ('soglia_controlli_demo', models.PositiveSmallIntegerField(default=1, help_text='Numero minimo di controlli (su 3) che devono matchare per bloccare un utente demo. 1 = basta 1 match, 3 = tutti e 3.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Impostazioni Sistema',
                'verbose_name_plural': 'Impostazioni Sistema',
            },
        ),
        migrations.AlterField(
            model_name='contenitore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oggettodacaricare',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oggettoposizionato',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pianodicarico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sezionecarico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vincolooggetto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vincolotraoggetti',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, help_text='ID account Google (sub) per OAuth2. Unico per utente.', max_length=255, null=True, unique=True)),
                ('trial_start', models.DateTimeField(blank=True, help_text='Data di inizio del periodo di prova.', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='Data di fine del periodo di prova (scadenza).', null=True)),
                ('is_paying', models.BooleanField(default=False, help_text='Utente pagante: accesso illimitato senza scadenza trial.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Utente Django associato.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utente',
            },
        ),
        migrations.CreateModel(
            name='DemoFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, help_text="SHA256 hash dell'IP del visitatore.", max_length=64)),
                ('browser_hash', models.CharField(blank=True, db_index=True, help_text='Hash del fingerprint del browser (JS lato client).', max_length=64, null=True)),
                ('cookie_token', models.CharField(blank=True, db_index=True, help_text='Token persistente firmato lato server, salvato nel cookie.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(help_text='Profilo utente associato a questo fingerprint.', on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='caricamento.userprofile')),
            ],
            options={
                'verbose_name': 'Fingerprint Demo',
                'verbose_name_plural': 'Fingerprint Demo',
                'indexes': [models.Index(fields=['ip_hash'], name='caricamento_ip_hash_3dc33c_idx'), models.Index(fields=['browser_hash'], name='caricamento_browser_a533b2_idx'), models.Index(fields=['cookie_token'], name='caricamento_cookie__e07bda_idx')],
                'unique_together': {('user_profile', 'ip_hash')},
            },
        ),
    ]
