# Generated by Django 6.0.7 on 2026-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0013_impostazionisistema_alter_contenitore_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impostazionisistema',
            name='google_client_id',
        ),
        migrations.RemoveField(
            model_name='impostazionisistema',
            name='google_client_secret',
        ),
        migrations.AlterField(
            model_name='contenitore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demofingerprint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='impostazionisistema',
            name='google_oauth_attivo',
            field=models.BooleanField(default=False, help_text="Abilita il pulsante 'Accedi con Google' sulla landing page. Richiede una Social Application Google configurata in 'Social applications' (Client ID + Secret da Google Cloud Console)."),
        ),
        migrations.AlterField(
            model_name='impostazionisistema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oggettodacaricare',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oggettoposizionato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pianodicarico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sezionecarico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vincolooggetto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vincolotraoggetti',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
