# Generated by Django 5.2.1 on 2026-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0015_aggiunto_archiviato_contenitore'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='archiviato',
            field=models.BooleanField(default=False, help_text="Se True, l'oggetto è archiviato e nascosto di default dalle liste."),
        ),
    ]
