# Generated by Django 5.2.1 on 2026-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caricamento", "0016_aggiunto_archiviato_oggetto"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="impostazioni_ottimizzatore",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Preferenze personali del workspace e dell'ottimizzatore.",
            ),
        ),
    ]
