# Generated by Django 6.0.7 on 2026-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0020_limite_soglia_controlli_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pianodicarico',
            name='soluzioni_alternative',
            field=models.JSONField(blank=True, default=list, help_text="Soluzioni alternative generate dall'ottimizzatore (anteprima/scelta)."),
        ),
    ]
