# Generated by Django 6.0.7 on 2026-08-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0021_pianodicarico_soluzioni_alternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pianodicarico',
            name='soluzioni_alternative',
        ),
    ]
