# Generated by Django 4.2 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caricamento", "0026_remove_legacy_blocca_posizionati"),
    ]

    operations = [
        migrations.AddField(
            model_name="oggettodacaricare",
            name="colore",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Colore esadecimale personalizzato per QUESTA riga di carico. Vuoto = usa il colore dell'anagrafica dell'oggetto.",
                max_length=7,
            ),
        ),
    ]
