# Generated by Django 6.0.7 on 2026-08-21 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0027_oggettodacaricare_colore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ls_customer_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID cliente su Lemon Squeezy.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_plan',
            field=models.CharField(blank=True, default='', help_text="Nome del piano acquistato (es. 'Mensile', 'Annuale').", max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text="Numero di utenti (seat) acquistati nell'abbonamento.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_subscription_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID abbonamento attivo su Lemon Squeezy.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_subscription_item_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID subscription-item per aggiornare la quantity.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_variant_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Variante Lemon Squeezy scelta (mensile/annuale).', null=True),
        ),
    ]
