# Generated by Django 6.0.7 on 2026-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0028_add_ls_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data/ora invio email di verifica.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', help_text='Token per la verifica email (monouso).', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email verificata tramite link di conferma.'),
        ),
    ]
