# Generated by Django 6.0.7 on 2026-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caricamento', '0029_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisistema',
            name='privacy_email',
            field=models.EmailField(default='info@carico3d.com', help_text="Email di contatto per l'esercizio dei diritti GDPR e per i rimborsi (mostrata in Privacy e Termini).", max_length=255),
        ),
        migrations.AddField(
            model_name='impostazionisistema',
            name='privacy_piva',
            field=models.CharField(blank=True, default='', help_text='Partita IVA / codice fiscale del titolare (facoltativo).', max_length=32),
        ),
        migrations.AddField(
            model_name='impostazionisistema',
            name='privacy_sede',
            field=models.CharField(blank=True, default='', help_text='Sede / indirizzo del titolare (campo facoltativo).', max_length=255),
        ),
        migrations.AddField(
            model_name='impostazionisistema',
            name='privacy_sito_url',
            field=models.URLField(default='http://127.0.0.1:8000', help_text='URL base del sito mostrato nelle pagine legali (in produzione impostare il dominio reale, es. https://carico3d.com).', max_length=255),
        ),
        migrations.AddField(
            model_name='impostazionisistema',
            name='privacy_titolare',
            field=models.CharField(default='Carico 3D', help_text="Nome del titolare del trattamento mostrato in Privacy e Termini (es. ragione sociale o nome dell'attività).", max_length=255),
        ),
    ]
