"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ta)6m@5)@%wjv61r!*rs%#q#upvj*t301eo@ub5s967!q*sa-k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Richiesto da django-allauth per Social Applications

    # Third-party
    'rest_framework',
    'corsheaders',
    'django_q',  # Coda task asincroni

    # Autenticazione social (Google OAuth2)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Local apps
    'caricamento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # django-allauth: richiesto per il funzionamento corretto
    'allauth.account.middleware.AccountMiddleware',
    # Trial: controllo scadenza periodo di prova
    'caricamento.middleware.TrialRequiredMiddleware',
]

# ---------------------------------------------------------------------------
# Django Q2 — Coda task asincroni
# ---------------------------------------------------------------------------

Q_CLUSTER = {
    "name": "carico_tridimensionale",
    "workers": 3,  # Numero di worker paralleli
    "recycle": 100,
    "timeout": 300,  # Timeout 5 minuti (calcolo geometrico)
    "retry": 360,  # Retry dopo 6 minuti
    "compress": True,
    "save_limit": 100,  # Mantiene le ultime 100 esecuzioni
    "queue_limit": 20,
    "cpu_affinity": 1,
    "label": "Ottimizzazione Carico 3D",
    # Usa il DB Django come backend (non richiede Redis)
    "django_db": True,
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'caricamento' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ---------------------------------------------------------------------------
# Autenticazione
# ---------------------------------------------------------------------------

LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/workspace/"
LOGOUT_REDIRECT_URL = "/"

# django-allauth
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    # Django default
    "django.contrib.auth.backends.ModelBackend",
    # allauth
    "allauth.account.auth_backends.AuthenticationBackend",
]

# django-allauth: social account settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # Le credenziali (client_id, secret) sono nel DB via SocialApp.
        # Non mettere "APP" qui: causerebbe MultipleObjectsReturned.
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# django-allauth: adapter personalizzato per credenziali Google da DB
SOCIALACCOUNT_ADAPTER = "caricamento.adapter.DynamicGoogleAdapter"

# django-allauth: account settings
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# ---------------------------------------------------------------------------
# Middleware personalizzato per trial
# ---------------------------------------------------------------------------
TRIAL_REQUIRED_PATHS = ["/workspace/"]
TRIAL_EXEMPT_PATHS = ["/", "/logout/", "/admin/", "/accounts/", "/api/"]


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.AcceptHeaderVersioning",
    "COERCE_DECIMAL_TO_STRING": True,
    # --- Rate Limiting (Throttling) ---
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "60/minute",        # 60 richieste API al minuto per utente
        "ottimizza": "10/minute",    # max 10 ottimizzazioni al minuto (6s ciascuna ≈ saturazione 100%)
    },
}


# ---------------------------------------------------------------------------
# CORS Headers (per sviluppo frontend)
# ---------------------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True  # Solo in sviluppo

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
