"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path


BASE_LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()

# Carica variabili d'ambiente dal file .env (solo in sviluppo)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fail fast: un secret di fallback potrebbe firmare sessioni e token con un
# valore noto. Il valore deve arrivare dal secret store o dal file .env locale.
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# Default a False: in produzione DEBUG va impostato esplicitamente a True
# solo se necessario. In sviluppo locale il .env lo mette a True.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Richiesto da django-allauth per Social Applications

    # Third-party
    'rest_framework',
    'corsheaders',
    'django_q',  # Coda task asincroni

    # Autenticazione social (Google OAuth2)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Local apps
    'caricamento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'caricamento.middleware.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # django-allauth: richiesto per il funzionamento corretto
    'allauth.account.middleware.AccountMiddleware',
    # Trial: controllo scadenza periodo di prova
    'caricamento.middleware.TrialRequiredMiddleware',
]

# ---------------------------------------------------------------------------
# Django Q2 — Coda task asincroni
# ---------------------------------------------------------------------------

Q_CLUSTER = {
    "name": "carico_tridimensionale",
    "workers": 3,  # Numero di worker paralleli
    "recycle": 100,
    "timeout": 300,  # Timeout 5 minuti (calcolo geometrico)
    "retry": 360,  # Retry dopo 6 minuti
    "compress": True,
    "save_limit": 100,  # Mantiene le ultime 100 esecuzioni
    "queue_limit": 20,
    "cpu_affinity": 1,
    "label": "Ottimizzazione Carico 3D",
    # Usa il DB Django come backend (non richiede Redis)
    "django_db": True,
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'caricamento' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Le PK sono AutoField (int) come da migrazioni esistenti: senza questo
# Django 5.x (default BigAutoField) proporrebbe continuamente una migrazione
# "Alter field id" su ogni modello. Per un DB già popolato l'auto-increment
# int32 è perfettamente adeguato e non richiede ALTER.
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL è l'unico database supportato (sviluppo e produzione).
# Le variabili DB_* sono OBBLIGATORIE: se mancano l'app NON parte
# (KeyError all'avvio), niente fallback silenzioso su SQLite.
# Valori in .env (sviluppo) o nelle env del container (produzione).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Raccolta dei file statici per la produzione (collectstatic).
# In Docker: volume condiviso con nginx; .gitignore esclude la cartella.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ---------------------------------------------------------------------------
# Autenticazione
# ---------------------------------------------------------------------------

LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/workspace/"
LOGOUT_REDIRECT_URL = "/"

# django-allauth
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    # Django default
    "django.contrib.auth.backends.ModelBackend",
    # allauth
    "allauth.account.auth_backends.AuthenticationBackend",
]

# django-allauth: social account settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # Le credenziali (client_id, secret) sono nel DB via SocialApp.
        # Non mettere "APP" qui: causerebbe MultipleObjectsReturned.
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# django-allauth: adapter personalizzato per credenziali Google da DB
SOCIALACCOUNT_ADAPTER = "caricamento.adapter.DynamicGoogleAdapter"

# django-allauth: account settings
ACCOUNT_LOGIN_METHODS = {"username"}  # login solo con username (non email)
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']  # username* = obbligatorio, email = opzionale
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# ---------------------------------------------------------------------------
# Middleware personalizzato per trial
# ---------------------------------------------------------------------------
TRIAL_REQUIRED_PATHS = ["/workspace/", "/api/"]
TRIAL_EXEMPT_PATHS = ["/logout/", "/admin/", "/accounts/"]


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "caricamento.api_errors.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.AcceptHeaderVersioning",
    "COERCE_DECIMAL_TO_STRING": True,
    # --- Rate Limiting (Throttling) ---
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "60/minute",        # 60 richieste API al minuto per utente
        "ottimizza": "10/minute",    # max 10 ottimizzazioni al minuto (6s ciascuna ≈ saturazione 100%)
    },
}


# ---------------------------------------------------------------------------
# CORS Headers — configurabili via env (default sicuri: niente allow-all)
# ---------------------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = (
    os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('true', '1', 'yes')
)
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if o.strip()
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


# ---------------------------------------------------------------------------
# Sicurezza HTTPS (consigliata in produzione, dietro nginx)
# Tutte configurabili via env: i default lasciano invariato lo sviluppo locale.
# ---------------------------------------------------------------------------

# Origini HTTPS autorizzate per il CSRF (es. "https://tuodominio.com")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# Redirect automatico a HTTPS (in produzione; altrimenti gestito da nginx)
SECURE_SSL_REDIRECT = (
    os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 'yes')
)

# Dietro nginx: Django deve sapere che la richiesta originale era HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Header di sicurezza indipendenti dal certificato: vengono applicati anche
# quando TLS è terminato da un proxy esterno.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Cookie sicuri (solo HTTPS)
SESSION_COOKIE_SECURE = (
    os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
)
CSRF_COOKIE_SECURE = (
    os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
)

# Logging esplicito su stdout: Docker/Gunicorn possono raccogliere i log
# senza scrivere file locali non persistenti nel container.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": BASE_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": BASE_LOG_LEVEL,
            "propagate": False,
        },
        "caricamento": {
            "handlers": ["console"],
            "level": BASE_LOG_LEVEL,
            "propagate": False,
        },
    },
}

# HSTS: abilitarlo solo quando il dominio è definitivamente servito in HTTPS.
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower()
    in ('true', '1', 'yes')
)
SECURE_HSTS_PRELOAD = (
    os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower()
    in ('true', '1', 'yes')
)
